### ISSUE TITLE
out 1 always outputs at 1x clock

### ISSUE THREAD

**Issue by ryokell** [cctvfm/covenlfo#3]
Setting up output 1 to a speed other than 1x clock speed would enable even more interesting divisions. Currently when this is set to 2 or higher, this output still matches clock speed (cycling back to a 1-led array doesn't change this output's rate).

**Comment by cctvfm** [comment]
I've rewritten some parts to allow output 1 to be any divider. Previously, the code didn't even check what the first divider was, it just assumed it would be 1. phasor calculation is now done on tempphasor, instead of using phasor1. 

In sync mode, we now check if any of the output dividers are 1 so that we can sync to every rising edge, and synccouter is cleared if any of the dividers have rolled over, including divider 1.
